<?php
/**
 * Plugin Name: Bespoke Cost Estimator (Armand Gilbert Web Design)
 * Description: Scaffolding custom calculator generated by gilbert.studio to replace legacy website calculator.
 * Version: 1.0.0
 * Author: gilbert.studio
 */

if (!defined('ABSPATH')) exit;

// 1. Register Shortcode [custom_estimator_form]
add_shortcode('custom_estimator_form', 'render_custom_estimator_form_armand_gilbert_web_design');

function render_custom_estimator_form_armand_gilbert_web_design() {
    ob_start();
    ?>
    <div class="custom-estimator-card" style="background:#f8fafc;border:1px solid #cbd5e1;border-radius:12px;padding:32px;max-width:500px;margin:20px auto;">
        <h3 style="margin-top:0;font-size:20px;font-weight:800;">Get a Quick Ballpark Estimate</h3>
        <form id="estimator-form">
        <div style="margin-bottom:15px;">
            <label style="display:block;margin-bottom:5px;font-weight:bold;">S</label>
            <input type="text" name="s" style="width:100%;padding:8px;border:1px solid #ccc;border-radius:4px;" />
        </div>

            <button type="submit" style="background:#ea580c;color:#fff;font-weight:bold;border:none;padding:12px 24px;border-radius:6px;cursor:pointer;width:100%;">Calculate Ballpark Cost →</button>
        </form>
        <div id="estimator-result" style="margin-top:20px;padding:15px;background:#fff;border:1px solid #e2e8f0;border-radius:6px;display:none;font-weight:bold;text-align:center;color:#1e293b;"></div>
    </div>
    
    <script>
    document.getElementById('estimator-form').addEventListener('submit', function(e) {
        e.preventDefault();
        // Custom simple calculation logic
        let resultDiv = document.getElementById('estimator-result');
        resultDiv.style.display = 'block';
        resultDiv.innerText = 'Calculating ballpark quote...';
        
        setTimeout(() => {
            resultDiv.innerHTML = '<span style="font-size:24px;color:#ea580c;">Estimated: $3,200 - $4,800</span><br/><span style="font-size:12px;color:#64748b;">(Ballpark only. We will call you to finalize.)</span>';
        }, 800);
    });
    </script>
    <?php
    return ob_get_clean();
}
